/*
1. EL NOMBRADO DEBE DECLARAR LA <INTENSIÓN>
2. NOMBRES DE CLASES DEBEN DE SER EN <SUSTANTIVO> E INICIAR EN <MINÚSCULA>
3. NOMBRES DE CLASES Y PAQUETES DEBEN DE SER EN <SUSTANTIVO>  E INICIAR EN <MAYÚSCULA>
4. NOMBRE DE MÉTODO/FUNCIÓN DEBE DE SER CON <VERBO> E INICIAR EN <MINÚSCULA>

 */